#### Write a pandas program to change the order of index of a given series

In [1]:
import pandas as pd

In [3]:
a=[1,2,3,4]
c=pd.Series(a)
c.reindex([1,3,2,0])

1    2
3    4
2    3
0    1
dtype: int64

##### write a python program to add,subtract,multiply,divide two series
##### [2,4,6,8],[1,3,5,7]

In [8]:
e=pd.Series([2,4,6,8])
o=pd.Series([1,3,5,7])
add=e+o
sub=abs(e-o)
mul=e*o
div=e/o
print("add=\n",add)
print("sub=\n",sub)
print("mul=\n",mul)
print("div=\n",div)

add=
 0     3
1     7
2    11
3    15
dtype: int64
sub=
 0    1
1    1
2    1
3    1
dtype: int64
mul=
 0     2
1    12
2    30
3    56
dtype: int64
div=
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
dtype: float64


In [15]:
d = {'addition' : pd.Series(add, index=[0,1,2,3]),
   'subtraction' : pd.Series(sub, index=[0,1,2,3]),
    'Multiplication':pd.Series(mul,index=[0,1,2,3]),
    'Division':pd.Series(div,index=[0,1,2,3])}
pd.DataFrame(d)

addition  subtraction  Multiplication  Division
0         3            1               2  2.000000
1         7            1              12  1.333333
2        11            1              30  1.200000
3        15            1              56  1.142857

#### write a python program to convert a pandas module series to python list

In [13]:
a=list(pd.Series([0,1,2,3]))
a

[0, 1, 2, 3]

In [11]:
list1=list(a)

In [12]:
list1

[0, 1, 2, 3]

#### write a pandas program to select the rows where the score is missing i.e is NaN sample data set

In [30]:
import numpy as np
exam_data={'name':['Sachin','Ganguly','Kohli','Johnson','Taylor','Waugh','Yuvraj','Kambli','Srinath','Munaf'],
          'Score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
          'attempts':[1,3,2,3,2,3,1,1,2,1],
          'Qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
labels=['a','b','c','d','e','f','g','h','i','j']
data=pd.DataFrame(exam_data,index=labels)

In [31]:
data

name  Score  attempts Qualify
a   Sachin   12.5         1     yes
b  Ganguly    9.0         3      no
c    Kohli   16.5         2     yes
d  Johnson    NaN         3      no
e   Taylor    9.0         2      no
f    Waugh   20.0         3     yes
g   Yuvraj   14.5         1     yes
h   Kambli    NaN         1      no
i  Srinath    8.0         2      no
j    Munaf   19.0         1     yes

In [37]:
data.loc['Score']

TypeError: Cannot index by location index with a non-integer key

In [39]:
data.loc?

#### write a pandas program to create todays date

In [41]:
import datetime

In [52]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [61]:
from datetime import date

In [64]:
date.today()

datetime.date(2019, 12, 28)

#### write a numpy program to create a 3x3 matrix with values ranging from 2to 10

In [78]:
l=[[2,3,4],[5,6,7],[8,9,10]]
arr=np.array(l)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### Illustrate the difference between ravel and flatten 

In [90]:
rav=arr.ravel()
arr[0][2]=67
rav

array([ 2,  3, 67,  5,  6,  7,  8,  9, 10])

In [106]:
flat=arr.flatten()
arr[0][1]=98

In [107]:
flat

array([ 2,  3, 67,  5,  6,  7,  8,  9, 10])